window.CGQ_CONFIG = {
  API_URL: "https://script.google.com/macros/s/AKfycbzAx2Y_qACK4hkdTooyT_-eYQ3UeTG5KnyqlaTZSAhaRNZdGl5ScU29HVVqM4OE9O_r/exec",
  REQUIRE_ONLINE_REPORTING: true,
  BRANCHES: [
    "A11 Residential - PHL2",
    "A62 Central People Development Center",
    "AYY Central Ayutthaya",
    "BBN Market Place Bangbon",
    "BNA Central Bangna",
    "CBR Central Chonburi",
    "CMA Central Chiangmai Airport",
    "CMI Central Chiangmai",
    "CMP Commercial Platform",
    "CRI Central Chiangrai",
    "CTR Central Chanthaburi",
    "CTW centralwOrld",
    "CWG Central Westgate",
    "CWN Central Chaengwattana",
    "CWT centralwOrld Offices",
    "DST Market Place Dusit",
    "EKM Ekkamai Lifestyle Center",
    "ESP Esplanade Ratchadapisek",
    "EVE CentralFestival East Ville (CANCEL)",
    "GOH GO HOTEL",
    "GTW G Tower Grand Rama 9",
    "HOF HOF",
    "HSF -",
    "HYI Central Hatyai",
    "ICY Central i-City",
    "JAV Market Place Thonglor",
    "KBI Central Krabi",
    "KKC Central Khon Kaen Campus",
    "KKN Central Khonkaen",
    "KTK Market Place Krungthep Kreeta",
    "LAV Market Place - La Villa",
    "LPG Central Lampang",
    "LPO Central Ladprao",
    "LSA Langsuan Colonade Apartment",
    "MHC Central Mahachai",
    "MJI Bquik-Meng Jai",
    "NKM Central Korat",
    "NKR Central Nakhon Si",
    "NKT Central Nakhonpathom",
    "NKW Central Nakhonsawan",
    "NLC Market Place Nanglinchee",
    "NTG The Ninth Towers Grand Rama 9",
    "NWC Market Place Nawamin",
    "NWF Market Place Nawamin Festival",
    "NWM Market Place Sukapiban 1",
    "PCU Market Place Pracha Uthit",
    "PDT Central Eastville",
    "PK2 Central Phuket Floresta",
    "PKO Central Pinklao",
    "PKS Petchkasem Power Center",
    "PKT Central Phuket Festival",
    "PNL Central Phitsanulok",
    "PTB Central Pattaya",
    "PTC Central Marina",
    "PTY Market Place Pattaya",
    "R4T ดุสิต ออฟฟิศ",
    "RCP Central Westville",
    "RID Central Ramindra",
    "RM2 Central Rama 2",
    "RM3 Central Rama 3",
    "RM4 ศูนย์การค้าเซ็นทรัล พาร์ค",
    "RM9 Central Rama 9",
    "RSD Residential All Project",
    "RST RST",
    "RTB Central Rattanathibet",
    "RYG Central Rayong",
    "RYT The Avenue Ratchayothin",
    "SBG The Shoppes at Belle Grand Rama 9",
    "SFD Mega Food Patio",
    "SKB Market Place Sukaphiban 3",
    "SLY Central Salaya",
    "SMI Central Samui",
    "SRC Central Si Racha",
    "SRT Central Suratthani",
    "SVB Central Village",
    "THL Marche Thonglor",
    "THR Market Place ThepRak",
    "UBN Central Ubon",
    "UDN Central Udon",
    "UHG Unilever House Grand Rama 9"
  ]
};
